- name: install and start ngnix
  hosts: frontend
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.package:
      name: ngnix
      state: present

  - name: start ngnix
    ansible.builtin.service:
      name: ngnix
      state: started
      enabled: yes