- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps, Linux, Shell, Ansible  # String
    name: "Sivakumar reddy M"
    gmail: info@GMAIL.COM
    # Dictionary == map
    tags:
      Application: payment
      Enviroment: dev
    # List
    listTags:
      - key: Application
        value: payment
      - key: Enviroment
        value: DevOps

  tasks:
    - name: default variable
      ansible.builtin.debug:
        msg: "Hello, {{ name | default('Ramesh') }}"

    # String to list
    - name: convert string to list
      ansible.builtin.debug:
        msg: "Technologies are: {{ technologies | split(',') }}"

    - name: convert map to list
      ansible.builtin.debug:
        msg: "Tags are: {{ tags | dict2items }}"

    - name: convert list into map
      ansible.builtin.debug:
        msg: "tag map: {{ listTags | items2dict }}"

    - name: read yaml and task it into variable
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"
    
    - name: convert yaml into json
      ansible.builtin.debug:
        msg: "json: {{ student_yaml | to_json }}"

    - name: save json to file
      ansible.builtin.copy:
        dest: ./student-data.json
        content: "{{ student_yaml | to_nice_json }}"

    - name: convert uppercase
      ansible.builtin.debug:
        msg: "{{ name | upper }}"

    - name: convert lowercase
      ansible.builtin.debug:
        msg: "{{ gmail | lower }}"